site_name: CxB RankPoint Simulator
site_mode: cxb
site_base: /
site_image_base: /images
site_style_base: /stylesheets
common_style_base: /common/stylesheets
common_script_base: /common/javascripts
description: 「CROSS×BEATS」のランクポイント表作成Webツールを公開しているサイトです。
session_key: cxbrank
secret:
environment: development
comrank_path: ../comrank
legacy_chart: true
adversary: false
edit_stop: 
service_end: 
#tracker_id:
#domain:
