site:
  name: REV. RankPoint Simulator
  style_pc: /style/pc.css
  style_sp: /style/sp.css
  mode: rev
  key: rev

db:
  adapter: mysql2
  host:
  username:
  password:
  database:

views:
  basedir: ../comrank/views

tracker:
  id: 
  domain: 
