site_name: REV. RankPoint Simulator
site_mode: rev_sunrise
site_base: /sunrise
site_image_base: /sunrise/images
site_style_base: /sunrise/stylesheets
site_common_script_base: /sunrise/common/javascripts
description: 「crossbeats REV. SUNRISE」のランクポイント表作成Webツールを公開しているサイトです。
style_pc: pc.css
style_sp: sp.css
session_key: revrank_sunrise
secret:
environment: development
comrank_path: ../../comrank
mydata_name: crossbeats REV. SUNRISE MY DATA
mydata_host: rev-srw.ac.capcom.jp
script_host: secure508.sakura.ne.jp/revtest.maplia.jp/sunrise
legacy_chart: false
edit_stop: 
#tracker_id:
#domain:
