source 'https://rubygems.org'
ruby '1.8.7'

gem 'rack-smartphone_detector'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra_more'
gem 'sinatra-jsonp'
gem 'sinatra-cross_origin'
gem 'sinatra-default_charset'

gem 'i18n', '~> 0.6.0'
gem 'mime-types', '~> 1.0'
gem 'padrino'

gem 'activerecord', '~> 2.3.18'
gem 'activerecord-mysql2-adapter'

gem 'json'
gem 'rinku'

gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'

gem 'haml'
