source 'https://rubygems.org'
ruby '1.8.7'

gem 'rack-mobile-detect'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-jsonp'
gem 'sinatra-cross_origin'
gem 'sinatra-default_charset'

gem 'activerecord', '~> 2.3.18'
gem 'activerecord-mysql2-adapter'

gem 'json'
gem 'rinku'

gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'
