source 'https://rubygems.org'

gem 'rails'
gem 'actionview'

gem 'rack'
gem 'rack-mobile-detect'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra_more'
gem 'sinatra-jsonp'
gem 'sinatra-cross_origin'
gem 'sinatra-default_charset'

gem 'i18n'
gem 'mime-types'

gem 'mysql2'

gem 'json'
gem 'rinku'

gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'

gem 'haml'
gem 'chronic'
